SET NAMES utf8mb4;
USE narita_db;
-- makers data (auto-generated from CSV)
INSERT INTO makers (id, row_group, kana_group, name, url, sort_order) VALUES
(1,'あ行','あ','株式会社　アカギ','http://www.akagi-nt.co.jp/',1),
(2,'あ行','あ','旭有機材工業株式会社','https://www.asahi-yukizai.co.jp/',2),
(3,'あ行','あ','株式会社　浅羽製作所','http://www.asaba-ss.co.jp/j/',3),
(4,'あ行','あ','愛知時計電機株式会社','https://www.aichitokei.co.jp/',4),
(5,'あ行','あ','アズビル金門株式会社','https://ak.azbil.com/',5),
(6,'あ行','あ','株式会社　アトムズ','http://www.atoms-corp.co.jp/',6),
(7,'あ行','あ','株式会社　アキヤマ','http://modoren-hose.net/',7),
(8,'あ行','あ','アスタム株式会社','http://www.astam.co.jp/',8),
(9,'あ行','あ','淡路マテリア株式会社','https://www.awaji-materia.co.jp/',9),
(10,'あ行','あ','アイシン産業株式会社','https://www.aishin-sangyo.co.jp/',10),
(11,'あ行','あ','アズビル株式会社','https://www.azbil.com/jp/',11),
(12,'あ行','い','因幡電機産業株式会社','https://www.inaba.co.jp/',12),
(13,'あ行','い','伊藤鉄工株式会社','http://www.i-g-s.co.jp/',13),
(14,'あ行','い','株式会社　イシザキ','https://ishizaki.biz/',14),
(15,'あ行','い','株式会社　立売堀製作所','http://www.itachibori.co.jp/',15),
(16,'あ行','い','株式会社　イノアック住環境','https://www.inoac.co.jp/',16),
(17,'あ行','い','株式会社　イトー鋳造','http://www.ito-chuuzou.com/',17),
(18,'あ行','い','株式会社　イノテック','http://www.inno-tech.jp/',18),
(19,'あ行','い','株式会社　イワキ','https://www.iwakipumps.jp/',19),
(20,'あ行','い','株式会社　石井マーク','http://www.ishiimark.com/',20),
(21,'あ行','い','株式会社　いけうち','https://www.kirinoikeuchi.co.jp/',21),
(22,'あ行','う','株式会社　上田コンクリート工業所','http://kkuedack.jp/',22),
(23,'あ行','う','ウツエバルブ株式会社','http://www.utsue-valve.co.jp/',23),
(24,'あ行','う','株式会社　ウォーターテック','https://www.nwatertec.co.jp/',24),
(25,'あ行','え','エヌケーケーシームレス鋼管株式会社',NULL,25),
(26,'あ行','え','株式会社　エーアンドエーマテリアル','https://www.aa-material.co.jp/',26),
(27,'あ行','え','エレポン化工機株式会社','https://www.elepon.co.jp/',27),
(28,'あ行','え','エウゼフロ－株式会社','http://www.euze-flow.co.jp/',28),
(29,'あ行','え','エヌパット株式会社','http://www.n-pat.co.jp/',29),
(30,'あ行','え','株式会社　エス・ブイ・エフ','http://www.svf.jp/',30),
(31,'あ行','お','株式会社　オーケーエム','http://www.okm-net.jp/',31),
(32,'あ行','お','株式会社　オンダ製作所','https://www.onda.co.jp/',32),
(33,'あ行','お','株式会社　大原鉄工所','https://www.oharacorp.co.jp/',33),
(34,'あ行','お','株式会社　オーヤラックス','http://www.oyalox.co.jp/',34),
(35,'あ行','お','株式会社　オーバル','https://www.oval.co.jp/',35),
(36,'あ行','お','株式会社　オーツカ','http://www.ohtsuka-jpn.co.jp/',36),
(37,'あ行','お','株式会社　大阪継手バルブ製作所','https://www.otvs.co.jp/',37),
(38,'あ行','お','小澤物産株式会社','http://www.ozawabussan.co.jp/',38),
(39,'あ行','お','大阪ラセン管工業株式会社','https://www.ork.co.jp/',39),
(40,'か行','か','株式会社　川本製作所','https://www.kawamoto.co.jp/',40),
(41,'か行','か','株式会社　川西水道機器','http://www.sk-kawanishi.com/',41),
(42,'か行','か','カナフレックスコーポレーション株式会社','https://kanaflex.co.jp/',42),
(43,'か行','か','株式会社　カクダイ','https://kakudai.jp/',43),
(44,'か行','か','株式会社　カワデン','http://www.kk-kawaden.co.jp/',44),
(45,'か行','か','株式会社　カワトＴ．Ｐ．Ｃ','https://www.kwt-tpc.co.jp/',45),
(46,'か行','か','金子産業株式会社','http://www.kaneko.co.jp/',46),
(47,'か行','か','川﨑機工株式会社','http://www.kawasakikikou.co.jp/',47),
(48,'か行','き','株式会社　協成','https://www.kyosei.com/',48),
(49,'か行','き','株式会社　キッツ','https://www.kitz.co.jp/',49),
(50,'か行','き','九州鋳鉄管株式会社','http://www.kyucyu.co.jp/index.htm',50),
(51,'か行','き','極東ゴム株式会社','http://www.kyokuto-rubber.co.jp/',51),
(52,'か行','き','株式会社　キッツエンジニアリングサービス','https://www.kesco.jp/',52),
(53,'か行','き','株式会社　キッツマイクロフィルター','https://www.kitzmf.com/',53),
(54,'か行','く','株式会社　栗本鐵工所','http://www.kurimoto.co.jp/',54),
(55,'か行','く','倉敷化工株式会社','https://www.kuraka.co.jp/',55),
(56,'か行','く','株式会社　クボタケミックス','https://www.kubota-chemix.co.jp/',56),
(57,'か行','く','クリモトポリマー株式会社','https://www.kuripoly.jp/',57),
(58,'か行','く','株式会社　クボタ','https://www.kubota.co.jp/',58),
(59,'か行','く','株式会社　倉野製作所','http://kurano-s.jp/',59),
(60,'か行','け','株式会社　ケー・エフ・シー','http://www.kfc-net.co.jp/',60),
(61,'か行','け','株式会社　ケイヒン','https://www.keihin-ve.co.jp/',61),
(62,'か行','こ','鋼栄工業株式会社','http://koei-kougyo.com/',62),
(63,'か行','こ','コスモ工機株式会社','https://www.cosmo-koki.co.jp/',63),
(64,'か行','こ','光陽産業株式会社','https://www.koyosangyo.co.jp/',64),
(65,'か行','こ','コンドーＦＲＰ工業株式会社','http://www.kondoh-frp.co.jp/',65),
(66,'か行','こ','株式会社　コンサス','https://www.consuss.co.jp/',66),
(67,'か行','こ','小岩金網株式会社','https://www.koiwa.co.jp/',67),
(68,'か行','こ','株式会社　光明製作所','https://www.komei-ss.co.jp/',68),
(69,'か行','こ','株式会社　小島製作所','https://www.kojima-core.co.jp/',69),
(70,'か行','こ','コンチネンタルシルマ－株式会社','http://www.conti-schilmer.com/',70),
(71,'か行','こ','株式会社　コーギケン','https://www.kohgiken.co.jp/',71),
(72,'さ行','さ','サンキン株式会社','https://www.sankin.co.jp/',72),
(73,'さ行','さ','サンコー機材株式会社','http://sankohkizai.co.jp/',73),
(74,'さ行','さ','サンワーカー株式会社','https://www.sanetsugroup.co.jp/sunworker/',74),
(75,'さ行','さ','ザムソン株式会社','http://samsonkk.co.jp/',75),
(76,'さ行','さ','サンエス護謨工業株式会社','https://www.sun-esu.co.jp/',76),
(77,'さ行','さ','株式会社　三協製作所','https://www.sankyo-s-s.co.jp/',77),
(78,'さ行','し','株式会社　昭和コーポレーション','https://www.showa-cp.jp/',78),
(79,'さ行','し','ショーボンドマテリアル株式会社','https://www.sb-material.co.jp/',79),
(80,'さ行','し','シーケー金属株式会社','https://www.ckmetals.co.jp/',80),
(81,'さ行','し','ジャパン・エンヂニアリング株式会社','https://www.japan-eng.co.jp/',81),
(82,'さ行','し','株式会社　昭和バルブ製作所','https://www.showavalve.co.jp/',82),
(83,'さ行','し','株式会社　昭和螺旋管製作所','https://www.showarasen.co.jp/',83),
(84,'さ行','し','下田エコテック株式会社','http://www.shimoda-ecotech.co.jp/',84),
(85,'さ行','し','株式会社　渋谷製作所','http://www.shibuya-seisakusyo.com/',85),
(86,'さ行','し','信越ポリマー株式会社','https://www.shinpoly.co.jp/',86),
(87,'さ行','し','株式会社　神港製作所',NULL,87),
(88,'さ行','し','株式会社　清水合金製作所','https://www.shimizugokin.co.jp/',88),
(89,'さ行','し','昭和鉄工株式会社','https://www.showa.co.jp/',89),
(90,'さ行','し','昭和機工株式会社','http://www.showakiko.co.jp/',90),
(91,'さ行','し','昭和機器計装株式会社','https://www.showa-kk.com/',91),
(92,'さ行','し','伸栄化学産業株式会社','https://www.shin-ei-chem.co.jp/',92),
(93,'さ行','す','スパイラックス・サーコリミテッド','https://www.spiraxsarco.com/global/ja-JP',93),
(94,'さ行','す','スペロセイキ株式会社','http://www.superoseiki.co.jp/',94),
(95,'さ行','す','菅尾工業株式会社','http://www.sugao.co.jp/',95),
(96,'さ行','す','スプレーイングシステムスジャパン合同会社','https://www.spray.co.jp/',96),
(97,'さ行','す','スリーエム工業株式会社','https://www.three-mmm.co.jp/',97),
(98,'さ行','す','水都工業株式会社','http://suito.jp.net/',98),
(99,'さ行','す','株式会社　水研','https://www.suiken.jp/',99),
(100,'さ行','す','角田鉄工株式会社','http://www.stk-valve.co.jp/',100),
(101,'さ行','す','株式会社　スリーボンド','https://www.threebond.co.jp/',101),
(102,'さ行','せ','積水化学工業株式会社','https://www.sekisui.co.jp/',102),
(103,'さ行','せ','積水アクアシステム株式会社','https://www.sekisuia.co.jp/',103),
(104,'さ行','せ','ゼンシン株式会社','http://www.zensin.co.jp/',104),
(105,'さ行','せ','積水成型工業株式会社','https://www.sekisuiseikei.co.jp/',105),
(106,'さ行','せ','センクシア株式会社','https://www.senqcia.co.jp/',106),
(107,'さ行','せ','ゼット工業株式会社','https://www.kyowa-z.co.jp/',107),
(108,'さ行','せ','西部機材株式会社','https://seibukizai.co.jp/',108),
(109,'さ行','せ','西邦工業株式会社','https://seiho.com/jp/',109),
(110,'た行','た','株式会社　多久製作所','http://www.tak-ss.co.jp/',110),
(111,'た行','た','ダイキン工業株式会社','https://www.daikin.co.jp/',111),
(112,'た行','た','ダイドレ株式会社','https://www.daidore.co.jp/',112),
(113,'た行','た','太三機工株式会社','http://www.dai3kiko.co.jp/',113),
(114,'た行','た','株式会社　竹村製作所','http://www.takemura-ss.com/',114),
(115,'た行','た','大成機工株式会社','https://www.taiseikiko.com/',115),
(116,'た行','た','有限会社　大日計器製作所','https://dainichi-keiki.com/',116),
(117,'た行','た','大同精密工業株式会社','http://www.daidoseimitu.co.jp/',117),
(118,'た行','た','株式会社　田中工業','https://www.otaru-tanaka.com/',118),
(119,'た行','た','第一高周波工業株式会社','https://dhf.co.jp/',119),
(120,'た行','た','大明金属工業株式会社','https://www.taimeikinzoku.co.jp/',120),
(121,'た行','た','大同工機株式会社','https://www.daidomachines.com/',121),
(122,'た行','た','タキロンシーアイシビル　株式会社','https://www.takiron-ci.co.jp/eng/',122),
(123,'た行','た','大東電材株式会社','https://www.daito-d.co.jp/',123),
(124,'た行','た','タイヨージョイント株式会社','https://www.taiyojoint.co.jp/',124),
(125,'た行','た','株式会社　大和鉄工所','http://www.daiwa-ir.jp/',125),
(126,'た行','た','大成化学工業株式会社','http://www.tci-taiseikagaku.co.jp/',126),
(127,'た行','た','株式会社　タブチ','https://www.tabuchi.co.jp/',127),
(128,'た行','た','株式会社　大東計器製作所','http://daitoukeiki.jp/',128),
(129,'た行','た','第一機材株式会社','https://www.dkc.jp/',129),
(130,'た行','た','タイフレックス株式会社','https://taiflex.net/',130),
(131,'た行','ち','千代田工業株式会社','https://www.chiyoda-kogyokk.jp/',131),
(132,'た行','ち','中部美化企業株式会社','https://www.chububika.co.jp/',132),
(133,'た行','つ','株式会社　鶴見製作所','https://www.tsurumipump.co.jp/',133),
(134,'た行','つ','鶴巻工業株式会社','http://tsurumaki-kogyo.jp/index.html',134),
(135,'た行','て','株式会社　テクノフレックス','https://www.technoflex.co.jp/',135),
(136,'た行','て','株式会社　テイエルブイ','https://www.tlv.com/ja/',136),
(137,'た行','て','テラル株式会社','https://www.teral.net/',137),
(138,'た行','と','東洋バルヴ株式会社','https://www.toyovalve.co.jp/',138),
(139,'た行','と','巴バルブ株式会社','https://www.tomoevalve.com/',139),
(140,'た行','と','東洋計器株式会社','https://www.toyo-keiki.co.jp/',140),
(141,'た行','と','東亜高級継手バルブ製造株式会社','http://www.toakoukyu.co.jp/',141),
(142,'た行','と','トラスコ中山株式会社','http://www.trusco.co.jp/',142),
(143,'た行','と','東拓工業株式会社','http://www.totaku.co.jp/',143),
(144,'た行','と','東栄管機株式会社','http://toeikanki.jp/',144),
(145,'た行','と','トーフレ株式会社','https://www.tofle.com/',145),
(146,'た行','と','東京計装株式会社','https://www.tokyokeiso.co.jp/',146),
(147,'た行','と','東洋平成ポリマー株式会社','https://www.toyo-heisei.co.jp/',147),
(148,'た行','と','株式会社　巴製作所','https://www.tomoe-works.co.jp/',148),
(149,'た行','と','特許機器株式会社','https://www.tokkyokiki.co.jp/',149),
(150,'た行','と','東レペフ加工品株式会社','http://www.toray-pef.co.jp/',150),
(151,'た行','と','株式会社　十川ゴム','https://www.togawa.co.jp/',151),
(152,'な行','な','株式会社　ナゴヤ','https://nagoya-pf.co.jp/',152),
(153,'な行','な','ナストーア株式会社','http://www.nastoa.co.jp/',153),
(154,'な行','な','株式会社　中山製鋼所','https://www.nakayama-steel.co.jp/',154),
(155,'な行','な','南国フレキ工業株式会社','https://www.nfk-jp.com/',155),
(156,'な行','な','株式会社　永島製作所','https://www.nagashima-f.co.jp/',156),
(157,'な行','な','内外ゴム株式会社','http://www.naigai-rubber.co.jp/',157),
(158,'な行','な','株式会社　ナガセ','https://www.net-nagase.co.jp/',158),
(159,'な行','な','株式会社　中村バルブ製作所','https://www.nv-s.jp/',159),
(160,'な行','な','株式会社　中北製作所','https://www.nakakita-s.co.jp/',160),
(161,'な行','に','日本鋳鉄管株式会社','https://www.nichu.co.jp/',161),
(162,'な行','に','日栄インテック株式会社','https://www.nichieiintec.jp/',162),
(163,'な行','に','日本ヴィクトリック株式会社','https://www.victaulic.co.jp/',163),
(164,'な行','に','日本ダイヤバルブ株式会社','http://www.ndv.co.jp/',164),
(165,'な行','に','株式会社　ニシヤマ','https://www.nishiyama.co.jp/',165),
(166,'な行','に','日本ボールバルブ株式会社','https://www.nbv.co.jp/',166),
(167,'な行','に','日本フローセル株式会社','http://www.flow-cell.co.jp/',167),
(168,'な行','に','日東バルブ株式会社','http://www.2110.co.jp/',168),
(169,'な行','に','日本プラスチック工業株式会社','https://www.nipplasi.co.jp/',169),
(170,'な行','に','日本スウェージロックＦＳＴ株式会社','https://www.japan.swagelok.solutions/',170),
(171,'な行','に','株式会社　日邦バルブ','https://www.nippov.co.jp/',171),
(172,'な行','に','日本ニューロン株式会社','https://www.neuron.ne.jp/',172),
(173,'な行','に','日本リックウィル株式会社','http://www.ric-nord.co.jp/ric/',173),
(174,'な行','に','株式会社　日弁特殊工業','http://www.nichiben.net/',174),
(175,'な行','に','日本エフ・アール・ピー株式会社','https://nihonfrp.co.jp/',175),
(176,'な行','に','日本エンコン株式会社','https://www.n-encon.co.jp/',176),
(177,'な行','に','日管工業株式会社','http://www.nikkan-kogyo.co.jp/',177),
(178,'な行','に','日本ギア工業株式会社','https://www.nippon-gear.jp/',178),
(179,'な行','に','日東精工株式会社','https://www.nittoseiko.co.jp/',179),
(180,'な行','に','日本ベンド株式会社',NULL,180),
(181,'な行','に','日本ヘルメチックス株式会社','http://www.nihon-hermetics.co.jp/',181),
(182,'な行','に','株式会社　日本レオナード商会','http://www.japan-leonard.co.jp/',182),
(183,'な行','に','日本バルブコントロールズ株式会社','https://www.valco.co.jp/',183),
(184,'な行','に','日本ピラー工業株式会社','https://www.pillar.co.jp/',184),
(185,'な行','に','日本継手株式会社','https://www.nippon-pf.co.jp/',185),
(186,'な行','ね','ネステック株式会社','https://www.nesstech.co.jp/',186),
(187,'な行','ね','ネグロス電工株式会社','https://www.negurosu.co.jp/',187),
(188,'な行','の','ノーラエンジニアリング株式会社','https://www.nowla.co.jp/',188),
(189,'な行','の','ノグチマテリアル株式会社','http://www.e-noguchi.co.jp/',189),
(190,'は行','は','株式会社　ハズ','https://www.has-jp.com/',190),
(191,'は行','は','株式会社　羽田パイプ製造所','http://www.haneda-pipe.co.jp/',191),
(192,'は行','は','株式会社　長谷川鋳工所','http://www.hasechuw.co.jp/',192),
(193,'は行','は','バクマ工業株式会社','https://www.bakuma.co.jp/',193),
(194,'は行','は','株式会社　ハウステック','https://www.housetec.co.jp/',194),
(195,'は行','は','株式会社　ヴァンテック','https://www.van-tecs.com/',195),
(196,'は行','ひ','株式会社　光合金製作所','https://www.hikarigokin.co.jp/',196),
(197,'は行','ひ','廣瀬バルブ工業株式会社','https://www.hirose-valves.co.jp/',197),
(198,'は行','ひ','日之出水道機器株式会社','https://hinodesuido.co.jp/',198),
(199,'は行','ひ','ビーエフ工業株式会社','https://www.bfkogyo.co.jp/',199),
(200,'は行','ひ','株式会社　昌立製作所','http://www.sfv.co.jp/',200),
(201,'は行','ふ','ブリヂストン化工品ジャパン株式会社','https://www.bridgestone-dpj.co.jp/',201),
(202,'は行','ふ','株式会社　プロテリアル','https://www.proterial.com/',202),
(203,'は行','ふ','株式会社　富士計器','https://www.fujikeiki.jp/',203),
(204,'は行','ふ','株式会社　フタワフランヂ製作所','https://www.futawa-flange.com/',204),
(205,'は行','ふ','古川工業株式会社','http://www.furukawa-valve.co.jp/',205),
(206,'は行','ふ','株式会社　藤井合金製作所','https://www.fujii-mfg.co.jp/',206),
(207,'は行','ふ','富士化工株式会社','http://www.fujikako.co.jp/',207),
(208,'は行','ふ','フシマン株式会社','https://www.fushiman.co.jp/',208),
(209,'は行','ふ','株式会社　フジトク','http://www.2219.co.jp/',209),
(210,'は行','ふ','福徳工業株式会社','https://hukutoku.co.jp/',210),
(211,'は行','ふ','株式会社　フジキン','https://www.fujikin.co.jp/',211),
(212,'は行','ふ','藤井高圧工業株式会社','http://www.fhpi.co.jp/',212),
(213,'は行','ふ','福西鋳物株式会社','https://www.fukunishiimono.co.jp/',213),
(214,'は行','ふ','フジクリーン工業株式会社','https://www.fujiclean.co.jp/',214),
(215,'は行','ふ','株式会社　福井製作所','http://www.fkis.co.jp/',215),
(216,'は行','ふ','富士工器株式会社','https://www.fujikoh-grp.co.jp/',216),
(217,'は行','へ','株式会社　ベンカン機工','http://benkankikoh.com/',217),
(218,'は行','へ','株式会社　ベンカン','https://www.benkan.co.jp/',218),
(219,'は行','へ','株式会社　ベルテクノ','https://www.beltecno.co.jp/',219),
(220,'は行','へ','株式会社　ベン','https://www.venn.co.jp/',220),
(221,'は行','へ','ヘンケルジャパン株式会社','https://www.henkel.co.jp/',221),
(222,'は行','へ','株式会社　ヘルメチック','https://www.hermetic.co.jp/',222),
(223,'は行','ほ','ホーコス株式会社','https://www.horkos.co.jp/',223),
(224,'は行','ほ','株式会社　ホクエイ','https://www.hokuei.co.jp/',224),
(225,'は行','ほ','北勢工業株式会社','https://www.hokusei-kogyo.co.jp/',225),
(226,'ま行','ま','前澤給装工業株式会社','http://www.qso.co.jp/',226),
(227,'ま行','ま','株式会社　牧村製作所','http://www.makimurass.co.jp/',227),
(228,'ま行','ま','前澤工業株式会社','https://www.maezawa.co.jp/ja/index.html',228),
(229,'ま行','ま','前田バルブ工業株式会社','https://www.mvk.co.jp/',229),
(230,'ま行','ま','株式会社　マサタニ','http://www.masatani.co.jp/',230),
(231,'ま行','ま','株式会社　マックピ－アンドエス','https://www.mac-ps.jp/',231),
(232,'ま行','み','ミヤコ株式会社','http://www.miyako-inc.jp/',232),
(233,'ま行','み','株式会社　ミヤワキ','https://www.miyawaki-inc.com/',233),
(234,'ま行','み','三井金属エンジニアリング株式会社','https://www.mesco.co.jp/',234),
(235,'ま行','み','三井化学産資株式会社','https://www.mitsui-sanshi.co.jp/',235),
(236,'ま行','み','未来工業株式会社','https://www.mirai.co.jp/',236),
(237,'ま行','め','明和工業株式会社','https://www.meiwajp.com/',237),
(238,'ま行','も','森松工業株式会社','http://www.morimatsu.jp/',238),
(239,'ま行','も','株式会社　本山製作所','https://www.motoyama-cp.co.jp/',239),
(240,'ま行','も','株式会社　森田鉄工所','http://morita-tekkousyo.co.jp/',240),
(241,'ま行','も','森永エンジニアリング株式会社','https://www.morieng.co.jp/',241),
(242,'ま行','も','モリ工業株式会社','https://www.mory.co.jp/',242),
(243,'や行','や','株式会社　大和バルブ','http://www.yamatovalve.co.jp/',243),
(244,'や行','や','山本計器製造株式会社','http://www.yamamotokeiki.co.jp/',244),
(245,'や行','や','山利商事株式会社','https://www.yamari-my.jp/',245),
(246,'や行','や','株式会社　山協製作所','https://www.sankyou-ss.jp/',246),
(247,'や行','ゆ','ユナイテッド・ジョイント合同会社','https://www.ujcompany.com/',247),
(248,'や行','よ','株式会社　ヨシタケ','https://www.yoshitake.co.jp/index.html',248),
(249,'や行','よ','ヨツギ株式会社','https://www.yotsugi.co.jp/',249),
(250,'や行','よ','株式会社　横田製作所','http://www.aquadevice.com/nippon/',250),
(251,'や行','よ','株式会社　横井製作所','https://www.yokoi.co.jp/',251),
(252,'や行','よ','株式会社　横河ブリッジ','http://www.yokogawa-bridge.co.jp/',252),
(253,'ら行','り','株式会社　リケン','https://www.riken.co.jp/',253),
(254,'ら行','れ','レッキス工業株式会社','http://www.rexind.co.jp/jp/',254),
(255,'わ行','わ','ワシノ機器株式会社','https://www.wasinokiki.co.jp/',255),
(256,'わ行','わ','株式会社　ワイエム技研','https://www.ymgiken.co.jp/',256),
(257,'アルファベット','J','ＪＦＥスチール株式会社','https://www.jfe-steel.co.jp/',257),
(258,'アルファベット','T','株式会社　ＴＯＺＥＮ','https://www.tozen.co.jp/',258),
(259,'アルファベット','J','ＪＦＥ溶接鋼管株式会社','https://www.jfe-wp.co.jp/',259),
(260,'アルファベット','K','株式会社　ＫＶＫ','https://www.kvk.co.jp/dev/',260),
(261,'アルファベット','S','ＳＡＮＥＩ株式会社','https://www.sanei.ltd/',261);